FROM python:3.12

# working directory
WORKDIR /backend

# install wkhtmltopdf and netcat
RUN apt-get update && apt-get install -y netcat-openbsd wkhtmltopdf && rm -rf /var/lib/apt/lists/*

# copy code
COPY /backend .

# install python dependencies
RUN pip install --no-cache-dir -r ./app/requirements.txt 

# expose port
EXPOSE 5000

# set the entrypoint
ENTRYPOINT ["./entrypoint.sh"]

# run the app
CMD ["flask", "run", "--host=0.0.0.0"]