FROM surnet/alpine-python-wkhtmltopdf:3.12.3-0.12.6-small

# working directory
WORKDIR /backend

# copy backend folder
COPY /backend .

# install python dependencies
RUN pip install -r ./app/requirements.txt

# Expose the port the app runs on
EXPOSE 5000

# Start the application
ENTRYPOINT ["./entrypoint.sh"]

CMD ["flask", "run", "--host=0.0.0.0"]
